services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Mount backend and frontend repositories in the same path used inside the Dockerfile
    volumes:
      - ./backend:/go-back
      - ./frontend/master:/go-back/frontend
      # Persist Go module cache across runs
      - go-mod-cache:/go/pkg/mod
    working_dir: /go-back
    # Expose the same ports as defined in the Dockerfile
    ports:
      - "3000:3000"   # Backend (Go/Wails)
      - "5173:5173"   # Frontend (Vite DevServer)
      - "34115:34115" # Wails DevWatcher
    # Default command starts the development server
    command: ["wails", "dev"]

# Define named volume for Go module cache
volumes:
  go-mod-cache:
    driver: local
