version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Mount all app directory inside /app in the container
    volumes: 
      - ./:/app
      # Ensure Go cache is persistent
      - go-mod-cache:/go/pkg/mod
    # Expose same ports as in Dockerfile
    ports:
      - "3000:3000"   # Backend (Go/Wails)
      - "8080:8080"   # Frontend (Wails server)
    # Define standard command
    command: ["wails", "dev"]

# Define named volume for Go module cache
volumes:
  go-mod-cache:
    driver: local