version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Mount the repository in the same path used inside the Dockerfile
    volumes:
      - ./:/go-back
      # Persist Go module cache across runs
      - go-mod-cache:/go/pkg/mod
    working_dir: /go-back
    # Expose the same ports as defined in the Dockerfile
    ports:
      - "3000:3000"   # Backend (Go/Wails)
      - "8080:8080"   # Frontend (Vite)
    # Default command starts the development server
    command: ["wails", "dev"]

# Define named volume for Go module cache
volumes:
  go-mod-cache:
    driver: local
