name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Lint, Test & Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: [app, server, ssg]
        steps:
            - name: Checout repo
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'pnpm'
                  cache-dependency-path: pnpm-lock.yaml
            
            - name: Enable Corepack
              run: corepack enable

            - name: Prepare pnpm
              run: corepack prepare pnpm@latest --activate

            - name: Install dependencies
              run: pnpm install
            
            - name: Install dependencies
              run: pnpm install

            - name: Lint ${{ matrix.package }}
              run: pnpm -filter ${{ matrix.package }} lint
            
            - name: Test ${{ matrix.package }}
              run: pnpm --filter ${{ matrix.package }} test

            - name: Build ${{ matrix.package }}
              run: pnpm --filter ${{ matrix.package }} build